export const typeBgColors = {
  normal: "bg-pokemon-normal",
  fire: "bg-pokemon-fire",
  water: "bg-pokemon-water",
  electric: "bg-pokemon-electric",
  grass: "bg-pokemon-grass",
  ice: "bg-pokemon-ice",
  fighting: "bg-pokemon-fighting",
  poison: "bg-pokemon-poison",
  ground: "bg-pokemon-ground",
  flying: "bg-pokemon-flying",
  psychic: "bg-pokemon-psychic",
  bug: "bg-pokemon-bug",
  rock: "bg-pokemon-rock",
  ghost: "bg-pokemon-ghost",
  dragon: "bg-pokemon-dragon",
  dark: "bg-pokemon-dark",
  steel: "bg-pokemon-steel",
  fairy: "bg-pokemon-fairy",
};

export const typeBorderColors = {
  normal: "border-pokemon-normal",
  fire: "border-pokemon-fire",
  water: "border-pokemon-water",
  electric: "border-pokemon-electric",
  grass: "border-pokemon-grass",
  ice: "border-pokemon-ice",
  fighting: "border-pokemon-fighting",
  poison: "border-pokemon-poison",
  ground: "border-pokemon-ground",
  flying: "border-pokemon-flying",
  psychic: "border-pokemon-psychic",
  bug: "border-pokemon-bug",
  rock: "border-pokemon-rock",
  ghost: "border-pokemon-ghost",
  dragon: "border-pokemon-dragon",
  dark: "border-pokemon-dark",
  steel: "border-pokemon-steel",
  fairy: "border-pokemon-fairy",
};

export const typeBgFaded = {
  normal: "bg-pokemon-normal/10",
  fire: "bg-pokemon-fire/10",
  water: "bg-pokemon-water/10",
  electric: "bg-pokemon-electric/10",
  grass: "bg-pokemon-grass/10",
  ice: "bg-pokemon-ice/10",
  fighting: "bg-pokemon-fighting/10",
  poison: "bg-pokemon-poison/10",
  ground: "bg-pokemon-ground/10",
  flying: "bg-pokemon-flying/10",
  psychic: "bg-pokemon-psychic/10",
  bug: "bg-pokemon-bug/10",
  rock: "bg-pokemon-rock/10",
  ghost: "bg-pokemon-ghost/10",
  dragon: "bg-pokemon-dragon/10",
  dark: "bg-pokemon-dark/10",
  steel: "bg-pokemon-steel/10",
  fairy: "bg-pokemon-fairy/10",
};
